### ISSUE TITLE
commerce.py syntax error line 297

### ISSUE THREAD

**Issue by mudgw2** [arctellion/StarBright#1]
Looks like there are missing commas...in line 297
po = [['Bulk Nutrients''Bulk Fibers''Bulk Organics''Bulk Minerals''Bulk Textiles''Exotic Flora'], #Raws

should be:
po = [['Bulk Nutrients','Bulk Fibers','Bulk Organics','Bulk Minerals','Bulk Textiles','Exotic Flora'], #Raws

Full array block below:
po = [['Bulk Nutrients''Bulk Fibers''Bulk Organics''Bulk Minerals''Bulk Textiles''Exotic Flora'], #Raws
['Art','Recordings','Writings','Tactiles','Osmancies','Wafers'], #Entertainments
['Strange Crystals','Strange Seeds','Pigments','Emotion Lighting','Silanes','Flora'], #Novelties
['Gemstones','Antiques','Collectibles','Allotropes','Spices','Seedstock'], #Rares
['Masterpieces','Exotic Flora','Antiques','Incomprehensibles','Fossils','VHDUS Emitter'], #Uniques
['In*','Ri*','Fl*','Ic*','Ag*','Va*']] #Imbalances

**Comment by arctellion** [comment]
hopefully the only one :) Fixed it now
